apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend-service
  labels:
    app: nginx-frontend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    app: nginx-frontend